# Generated by Django 5.1.5 on 2025-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='type',
        ),
        migrations.AddField(
            model_name='projects',
            name='kpi_file',
            field=models.FileField(null=True, upload_to='excel_files/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
