# Generated by Django 5.1.5 on 2025-01-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_projects_file_remove_projects_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='kpi_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='media_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='kpi_file',
            field=models.FileField(blank=True, null=True, upload_to='kpi_files/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
