# Generated by Django 5.0.3 on 2025-03-03 05:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projects_kpi_file_alter_projects_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='kpi_file',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='projects',
            name='media_file',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
