# Generated by Django 5.1.5 on 2025-06-02 03:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_projects_kpi_file_alter_projects_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='google_sheet_ids',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
