# Generated by Django 5.1.5 on 2025-06-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_savedscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('plot_config', models.JSONField()),
                ('chart_data', models.JSONField()),
                ('chart_options', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'project', 'file_type', 'file_name', 'sheet_name')},
            },
        ),
    ]
