# Generated by Django 5.1.5 on 2025-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_savedplot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedplot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedplot',
            name='plot_name',
            field=models.CharField(default='Default Plot', max_length=255),
        ),
    ]
