# Generated by Django 5.1.5 on 2025-06-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_savedplot_unique_together_savedplot_plot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pivot_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('pivot_config', models.JSONField()),
                ('pivot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'project', 'pivot_name')},
            },
        ),
    ]
