# Generated by Django 5.1.5 on 2025-06-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_savedpivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPivotPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(default='Default Pivot Plot', max_length=255)),
                ('plot_config', models.JSONField()),
                ('chart_data', models.JSONField()),
                ('chart_options', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pivot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.savedpivot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'project', 'pivot', 'plot_name')},
            },
        ),
    ]
