# Generated by Django 5.1.5 on 2025-06-17 06:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_savedpivotplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='concatenated_file',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
