# Generated by Django 5.1.5 on 2025-06-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpivotplot',
            name='active_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
