# Generated by Django 5.1.5 on 2025-07-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_api_log_model'),
        ('api', '0016_savedpivotplot_active_filters'),
    ]

    operations = [
    ]
