# Generated by Django 5.1.5 on 2025-07-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_request_files_to_apilog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_user_id_16aa10_idx',
            old_name='api_apilog_user_id_2a8b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_endpoin_dd64da_idx',
            old_name='api_apilog_endpoin_8c8b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_respons_7f2b5c_idx',
            old_name='api_apilog_respons_9c8b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_project_981bcb_idx',
            old_name='api_apilog_project_0c8b8c_idx',
        ),
    ]
