# Generated by Django 5.1.5 on 2025-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_api_apilog_user_id_2a8b8c_idx_api_apilog_user_id_16aa10_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='request_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
