# Generated by Django 5.1.5 on 2025-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_apilog_request_body_apilog_request_content_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_user_03e010_idx',
            old_name='api_apilog_user_id_16aa10_idx',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='request_body',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='request_content_type',
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
