# Generated by Django 5.1.5 on 2025-07-07 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_api_apilog_user_id_16aa10_idx_api_apilog_user_03e010_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apilog',
            new_name='api_apilog_user_id_16aa10_idx',
            old_name='api_apilog_user_03e010_idx',
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
