# Generated by Django 5.1.5 on 2025-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_api_apilog_user_03e010_idx_api_apilog_user_id_16aa10_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apilog',
            name='api_apilog_user_id_16aa10_idx',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='user',
        ),
        migrations.AddField(
            model_name='apilog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user_id', 'request_timestamp'], name='api_apilog_user_id_16aa10_idx'),
        ),
    ]
