# Generated by Django 5.1.5 on 2025-07-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_otptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDAPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(default='EDA Plot', max_length=255)),
                ('plot_type', models.CharField(choices=[('histogram', 'Histogram'), ('boxplot', 'Box Plot'), ('scatter', 'Scatter Plot'), ('correlation', 'Correlation Matrix'), ('missing_values', 'Missing Values'), ('distribution', 'Distribution Plot'), ('heatmap', 'Heatmap'), ('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('custom', 'Custom Plot')], default='custom', max_length=20)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_config', models.JSONField(default=dict)),
                ('chart_data', models.JSONField(default=dict)),
                ('chart_options', models.JSONField(default=dict)),
                ('eda_analysis_type', models.CharField(blank=True, max_length=100, null=True)),
                ('columns_analyzed', models.JSONField(default=list)),
                ('data_summary', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'project', 'plot_name')},
            },
        ),
    ]
