# Generated by Django 5.1.5 on 2025-07-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_edaplot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDAFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=255)),
                ('format_type', models.CharField(choices=[('single_plot', 'Single Plot Format'), ('multi_plot', 'Multi-Plot Flow'), ('dashboard', 'Dashboard Format'), ('analysis_flow', 'Analysis Flow')], default='single_plot', max_length=20)),
                ('format_config', models.JSONField(default=dict)),
                ('required_columns', models.JSONField(default=list)),
                ('optional_columns', models.JSONField(default=list)),
                ('column_patterns', models.JSONField(default=dict)),
                ('sample_data_structure', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'format_name')},
            },
        ),
    ]
