# Generated by Django 5.1.5 on 2025-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_edaformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edaformat',
            name='format_type',
            field=models.CharField(choices=[('single_plot', 'Single Plot'), ('multi_plot', 'Multi Plot'), ('dashboard', 'Dashboard'), ('analysis_flow', 'Analysis Flow')], default='single_plot', max_length=20),
        ),
        migrations.AlterField(
            model_name='edaformat',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
