# Generated by Django 5.1.5 on 2025-10-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_edaformat_format_type_alter_edaformat_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpivotplot',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
