# Generated by Django 5.1.5 on 2025-10-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_insights_to_savedpivotplot'),
    ]

    operations = [
    ]
