# Generated by Django 5.1.5 on 2025-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_order_to_savedpivotplot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpivotplot',
            name='insights',
        ),
        migrations.AddField(
            model_name='savedpivotplot',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
