from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('getCommits/',views.GetSpecificSheetCommits.as_view(),name='get_commits'),
    path('getCommitsArray/',views.GetSpecificSheetCommitsArray.as_view(),name='get_commits_array'),
    path('undo-redo/',views.UndoRedoSheet.as_view(),name='get_commits'),
    path('merge/',views.MergeFile.as_view(),name='merge_file'),
    path('download/',views.Save.as_view(),name='download_file'),
    path('upload/', views.FileUploadView.as_view(), name='upload_file'),
    # path('clean/', views.Cleaning.as_view(), name='clean_file'),
    path('cleaning/', views.CleaningColumns.as_view(), name='clean_file'),
    path('melting/', views.Melting.as_view(), name='melt_file'),
    path('mapping/',views.Mapping.as_view(), name='mapping_file'),
    # path('sheet/<str:sheet_name>/', views.SheetDataView.as_view(), name='get_sheet_data'),
    path('auth/signup/', views.SignupView.as_view(), name='signup'),
    path('auth/signin/', views.SigninView.as_view(), name='signin'),
    path('auth/upload/', views.UploadProject.as_view(), name='upload'),
    path('auth/projects/', views.UserProjectsView.as_view(), name='projects'),
    path('auth/projects/delete', views.DeleteProject.as_view(), name='projects'),
    path('update/', views.UpdateProject.as_view(), name='update_project'),
    path('info/', views.SheetInfo.as_view(), name='sheet_info'),
    path('eda/', views.EnhancedEDAAnalysis.as_view(), name='eda_analysis'),
    # path('eda-personalized/', views.PersonalizedEDAAnalysis.as_view(), name='personalized_eda_analysis'),
    path('pivot-eda/', views.PivotEDAAnalysis.as_view(), name='pivot_eda_analysis'),
    path('download-eda-excel/', views.DownloadEDAExcel.as_view(), name='download_eda_excel'),
    path('download-eda-pptx/', views.DownloadEDAPPTX.as_view(), name='download_eda_pptx'),
    # path('download-personalized-eda-excel/', views.DownloadPersonalizedEDAExcel.as_view(), name='download_personalized_eda_excel'),
    # path('download-personalized-eda-pptx/', views.DownloadPersonalizedEDAPPTX.as_view(), name='download_personalized_eda_pptx'),
    path('sheet-commit-graph/', views.SheetCommitGraph.as_view(), name='sheet_commit_graph'),
    path('add-date/', views.AddDateColumns.as_view(), name='add_date_columns'),
    path('create_google_sheet/', views.CreateGoogleSheet.as_view(), name='create_google_sheet'),
    path('update_from_google_sheet/', views.UpdateFromGoogleSheet.as_view(), name='update_from_google_sheet'),
    path('auth/file/delete/', views.DeleteFile.as_view(), name='delete_file'),
    path('custom-script/', views.CustomScriptRun.as_view(), name='custom-script'),
    # path('custom-script-run/', views.CustomScriptRun.as_view(), name='custom-script-run'),
    path('save_script/', views.SaveScript.as_view(), name='save_script'),
    path('fetch_scripts/', views.FetchScripts.as_view(), name='fetch_scripts'),
    path('concatenate-sheets/', views.ConcatenateSheets.as_view(), name='concatenate_sheets'),
    path('save-plot/', views.SavePlot.as_view(), name='save_plot'),
    path('fetch-plots/', views.FetchPlots.as_view(), name='fetch_plots'),
    path('project-details/', views.ProjectDetails.as_view(), name='project-details'),
    path('save-report-pivot/', views.SaveReportPivot.as_view(), name='save_report_pivot'),
    path('fetch-report-pivot/', views.FetchReportPivot.as_view(), name='fetch_report_pivot'),
    path('delete-report-pivot/', views.DeleteReportPivot.as_view(), name='delete_report_pivot'),
    path('save-pivot-plot/', views.SavePivotPlot.as_view(), name='save_pivot_plot'),
    path('delete-pivot-plot/', views.DeletePivotPlot.as_view(), name='delete_pivot_plot'),
    path('fetch-pivot-plots/', views.FetchPivotPlots.as_view(), name='fetch_pivot_plots'),
    path('download-pivot-ppt/', views.DownloadPivotPPT.as_view(), name='download_pivot_ppt'),
    path('download-pivot-excel/', views.DownloadPivotExcel.as_view(), name='download_pivot_excel'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
